### ISSUE TITLE
Depends on old version of snap

### ISSUE THREAD

**Issue by nomeata** [mightybyte/snaplet-acid-state#17]
Hi,

please upload a version compatible with snap 0.14.

I’d also suggest you to add your package to stackage, to noticed such issues earlier, and for some free QA: http://www.stackage.org/authors 

This would greatly help downstream distribution packagers.

Thanks,
Joachim

**Comment by mightybyte** [comment]
Fixed

**Comment by nomeata** [comment]
Thanks!
